### ISSUE TITLE
Request to support Gnosis Beacon Chain

### ISSUE THREAD

**Issue by ulyanas** [stake-house/wagyu-key-gen#131]
Hi, Stake House!
Would be great to have support for the Gnosis Beacon Chain in the Waguy key generator. 

https://www.xdaichain.com/for-validators/consensus/sbc

https://docs.gnosischain.com/

Could you please contact me on Telegram? I am happy to provide more details.

Ulyana
Gnosis Beacon Chain PM
Telegram @ulyanaskl

**Comment by alexpeterson91** [comment]
Please do this!  I will even start my own work on a fork to include Gnosis Chain since the community very much wants this and the base deposit_CLI code changes to include Gnosis chain alongside Ethereum are minimal, so this shouldn't present too much of a problem

**Comment by colfax23** [comment]
Hi both!  This sounds like a great addition.  We're very low bandwidth right now, and would like this to be an open tool for the community to contribute to & maintain, so I'd love for you to work on it and send a PR and we'll take a look.

**Comment by alexpeterson91** [comment]
> Hi both! This sounds like a great addition. We're very low bandwidth right now, and would like this to be an open tool for the community to contribute to & maintain, so I'd love for you to work on it and send a PR and we'll take a look.


I've done work on the backend https://github.com/dappnode/wagyu-key-gen, changes were minor, not gonna do a PR or anything yet since our fork is focusing on Gnosis chain and therefore we made it default, I'll be sure to make a new branch myself and do the added PR for the backend separately. anyways this my WIP so far for adding gnosis, so far all the work was done on the backend and the gnosis stuff was written for  ETH version 2.0, not the current version still in the master branch here, but it was simple enough to translate, and will be simpler when you do upgrade since the code is already written anyway.  Now for the more tedious and difficult part, front-end. 
Glad to be involved!

- [X] Backend - @alexpeterson91 / Voss
- [ ] Frontend - @alexpeterson91 / Voss + ?

**Comment by alexpeterson91** [comment]
@colfax23 i should have my code ready for a PR just to add gnosis to the current main branch in a day or 2. Work is done works in dev environment just have a few UI tweaks because a couple added notes don't fit well in the UI. Curious how progress is on your major upgrade to the 2.0 ETH deposit CLI? I've been following the code a bit but don't know where it's at yet. Not sure if i should work on cleaning my PR up perfectly for the current main version or if I should work on adding it to the new version. Gnosis uses the newer CLI as a base anyway in their keygen software. Thanks in advance!

**Comment by remyroy** [comment]
@alexpeterson91 I think you will find most of the code for integration with version 2.0 of the staking-deposit-cli in #136

**Comment by alexpeterson91** [comment]
> @alexpeterson91 I think you will find most of the code for integration with version 2.0 of the staking-deposit-cli in #136 

I did find that already. Thanks.  I was just wondering if I should focus on making gnosis work for that PR or for the current main branch.

**Comment by remyroy** [comment]
@alexpeterson91 That PR is not merged yet, but you should probably base your work on that since it has major internal changes and there is likely some intersections with your work.

**Comment by alexpeterson91** [comment]
@remyroy got it. I had to back port a small portion of the python to do the main branch since gnosis is based off the newer CLI to make it work on the current main branch. 
I'll work on both this week. The main branch is already fully functional just needs to be cleaned up a little bit. And I'll get working on the next version as well this week.

**Comment by alexpeterson91** [comment]
@remyroy just submitted a PR https://github.com/remyroy/wagyu-key-gen/pull/1 to your branch, got things all functional for gnosis please let me know how it looks.  theres a few things id like to modify but they are not necessary at this time, I can add them later.

**Comment by alexpeterson91** [comment]
> @remyroy just submitted a PR [remyroy#1](https://github.com/remyroy/wagyu-key-gen/pull/1) to your branch, got things all functional for gnosis please let me know how it looks. theres a few things id like to modify but they are not necessary at this time, I can add them later.

video demo: https://youtu.be/RvSM0LQKqtU

**Comment by remyroy** [comment]
As mentioned in #141, we prefer to keep Wagyu Key Gen dedicated to Ethereum only.
