### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by colfax23** [stake-house/wagyu-key-gen#3]
Implement a progress bar to signify how far along in the process you are, so the user knows how many steps remain.

**Comment by rhythnic** [comment]
@colfax23 I've been thinking about how to integrate the Stepper component, and I have a few thoughts that I'll capture here.

To have a Stepper that's visible in all the routes except for home, there needs to be a global state variable for the current step index.  We also need each route (except for home) to import step configuration (array of objects), and the UI components for displaying steps and step navigation.  Rather than trying to synchronize the display of the Stepper across all 3 components, it would be easier to display it in a parent component.  We could also store global state in the parent component.

These are some thoughts about the architecture from the perspective of using a Stepper.

## Overview
- Except for the home route, all routes share a parent component that contains all state and state setters
- Each step has its own route, along the lines of `/mnemonicgeneration/copymnemonic`, `/mnemonicimport/confirmpassword`, etc.  The parent component analyzes the route to determine the step configuration and the current step.  There would be 2 possible sequences of steps, based on mnemonic import or generation, and both sequences would contain the key generation steps.
- The parent component renders the current step, and below it the stepper UI and navigation (back/forward)
- Navigation back/forward through steps is accomplished via the router
- The parent passes the state and setters needed by the step component as props
- Steps can share the component by which they are rendered, so likely we can use `KeyGenerationWizard`, `MnemonicGenerationWizard`, and `MnemonicImport` without too much modification.

**Comment by rhythnic** [comment]
One route per step might not be a good idea, since it's not visible anyways, and if it were, it would allow the user to jump around randomly.  Maybe route could signify sequence of steps, and state is used to track the current step.
